### ISSUE TITLE
Complete jre/jdk core-plan deprecation

### ISSUE THREAD

**Issue by gavindidrichsen** [gavindidrichsen/core-plans#9]
### Outstanding Tasks
- [x] Scott confirmed merge is fine with existing jenkins #2849 and jruby1 #2875 PRs.  No need to rebase them from master to refresh/2019q3. See [my comment](https://github.com/habitat-sh/core-plans/issues/2810#issuecomment-518656932)
- [x] Waiting on 2 final PRs to be merged: jenkins #2849 and gocd-server #2957
- [x] Close the tracking issue #2810

### Context
[Scott's list of core plans for jre/jdk deprication](https://github.com/habitat-sh/core-plans/issues/2810)

### Completed Tasks
- [x] Fix the core/cerebro service bats tests to pass with old core/jdk
- [x] Raise draft core/cerebro PR #2845 with service tests all fixed
- [x] Raise draft core/jenkins PR #2849 with service tests all fixed
- [x] Raise draft core/sbt PR #2852 with tests all fixed
- [x] Finish verifying core/sbt,sumologic before introducing the openjdk
- [x] Rebuilt with openjdk11 all 5 plans with working tests and identified 2 service failures (logstash, ...then go on to the other 14 without tests
- [x] Finish build assessment for all plans
- [x] Time permitting, add tests to the 14 plans that don't have tests
